# Generated by Django 4.0.6 on 2022-07-06 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeoforganizationmodel',
            name='OrganizationNetwork',
        ),
        migrations.RemoveField(
            model_name='organizationsmodel',
            name='TypeOfOrganization',
        ),
        migrations.DeleteModel(
            name='OrganizationNetworkModel',
        ),
        migrations.DeleteModel(
            name='TypeOfOrganizationModel',
        ),
    ]
