# Generated by Django 4.0.6 on 2022-07-06 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_remove_typeoforganizationmodel_organizationnetwork_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfOrganizationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='turi')),
            ],
            options={
                'verbose_name': 'Tashkilot turi',
                'verbose_name_plural': 'Tashkilot turlari',
            },
        ),
        migrations.CreateModel(
            name='OrganizationNetworkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Tur')),
                ('typeOfOrganization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.typeoforganizationmodel', verbose_name='type')),
            ],
            options={
                'verbose_name': "Tashkilot tarmog'i",
                'verbose_name_plural': "Tashkilot tarmog'lari",
            },
        ),
    ]
