# Generated by Django 4.0.6 on 2022-07-06 01:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_organizationsmodel_organizationnetworkmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtmodel',
            name='regions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.regionmodel', verbose_name='Viloyat'),
        ),
        migrations.AlterField(
            model_name='organizationsmodel',
            name='OrganizationNetworkModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.organizationnetworkmodel', verbose_name="tarmog'i"),
        ),
        migrations.AlterField(
            model_name='organizationsmodel',
            name='districts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.districtmodel', verbose_name='Tuman'),
        ),
        migrations.CreateModel(
            name='MahallaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Mahalla')),
                ('sector', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)], verbose_name='Sector')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.districtmodel', verbose_name='Tuman')),
            ],
            options={
                'verbose_name': 'Mahalla',
                'verbose_name_plural': 'Mahallalar',
            },
        ),
        migrations.AddField(
            model_name='organizationsmodel',
            name='mahalla',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='organization.mahallamodel', verbose_name='Mahalla'),
            preserve_default=False,
        ),
    ]
